name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Hoặc nhánh bạn muốn trigger

jobs:
  build-deploy:           # job id
    runs-on: ubuntu-latest  # runs-on phải nằm dưới job id
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: echo "Build your project here"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Thư mục build
